<?php
/**
 * MM Ajax 
 *
 *
 * @category    design
 * @package     base_default
 * @copyright    Copyright (c) 2015 MM (http://blog.meumagento.com.br/)
 * @author       MM (Thiago Caldeira de Lima) AFL 3.0)
 */
?>
<div>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
</div>

<select id="selectFood">
    <option value="drinks">Drinks</option>
    <option value="foods">Foods</option>
</select>
<div id="ajaxContent"></div>

<script type="text/javascript">
var _urlAjax = "<?php echo $this->getAjaxUrl()?>";
new Ajax.Updater('ajaxContent', _urlAjax, {
          method: 'get',
          parameters: {'_type' : 'drinks'} // if neccessary
        });

$('selectFood').observe('change', function(event){

    var select = Event.element(event);
   
    new Ajax.Updater('ajaxContent', _urlAjax, {
      method: 'get',
      parameters: {'_type' : select.value }
    });

});
</script>